apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifact-keeper

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - minio-statefulset.yaml
  - backend-deployment.yaml
  - edge-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: artifact-keeper
  app.kubernetes.io/managed-by: kustomize

# Image customization - override in overlays
images:
  - name: artifact-keeper-backend
    newTag: latest
  - name: artifact-keeper-edge
    newTag: latest
