{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "artifact-keeper.serviceAccountName" . }}
  labels:
    {{- include "artifact-keeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
